services:
  messenger:
    container_name: messenger
    build:
      context: ./messenger
      dockerfile: ./Dockerfile
    ports:
     - 8080:8080
    env_file:
     - path: ./messenger/.env
    depends_on:
      rabbitmq:
        condition: service_healthy 
      redis:
        condition: service_healthy
      # зависимость во время локальной разработки
      migrations:
        condition: service_completed_successfully
    networks:
     - realtime

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
     - realtime

  redis:
    image: redis:8.4-alpine
    container_name: redis
    ports:
     - "6379:6379"
    environment:
      REDIS_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
     - realtime

  # postgresql для локальной разработки
  postgresql:
    image: postgres:18-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messenger_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d messenger_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - realtime

  # миграции для локальной разработки
  migrations:
    image: migrate/migrate
    container_name: migrations
    volumes:
      - ./messenger/migrations:/migrations
    command: 
      - -path=/migrations/
      - -database=postgres://postgres:password@postgresql:5432/messenger_db?sslmode=disable
      - up
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - realtime

networks:
  realtime:
    driver: bridge